[package]
name = "xmobar-slots"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xmobet"
path = "src/main.rs"

[dependencies]
confy = "0.5.1"
random = "0.13.2"
serde = { version = "1.0.152", features = ["derive"] }
signal-hook = "0.3.14"
toml = "0.7.2"
